import logging

CONF_ID = "id"
CONF_CURRENCY_NAME = "currency_name"
CONF_MINER_ADDRESS = "miner_address"
CONF_UPDATE_FREQUENCY = "update_frequency"
CONF_NAME_OVERRIDE = "name_override"
CONF_TOKEN = "token"
CONF_SOLO = "solo"

SENSOR_PREFIX = "2minersInfo "

ATTR_CURRENT_HASHRATE_MH_SEC = "current_hashrate_mh_sec"
ATTR_ACTIVE_WORKERS = "active_workers"
ATTR_CURRENT_HASHRATE = "current_hashrate"
ATTR_INVALID_SHARES = "invalid_shares"
ATTR_LAST_UPDATE = "last_update"
ATTR_REPORTED_HASHRATE = "reported_hashrate"
ATTR_STALE_SHARES = "stale_shares"
ATTR_UNPAID = "unpaid"
ATTR_VALID_SHARES = "valid_shares"
ATTR_START_BLOCK = "start_block"
ATTR_END_BLOCK = "end_block"
ATTR_AMOUNT = "amount"
ATTR_TXHASH = "txhash"
ATTR_PAID_ON = "paid_on"
ATTR_AVERAGE_HASHRATE_24h = "average_hashrate_24h"
ATTR_SINGLE_COIN_LOCAL_CURRENCY = "single_coin_in_local_currency"
ATTR_TOTAL_UNPAID_LOCAL_CURRENCY = "unpaid_in_local_currency"
ATTR_COINS_PER_MINUTE = "coins_per_minute"
ATTR_TOKEN_NAME = "token_name"

BTG_API_ENDPOINT = "https://btg.2miners.com/api"
SOLO_BTG_API_ENDPOINT = "https://solo-btg.2miners.com/api"
ZEC_API_ENDPOINT = "https://zec.2miners.com/api"
SOLO_ZEC_API_ENDPOINT = "https://solo-zec.2miners.com/api"
ZEN_API_ENDPOINT = "https://zen.2miners.com/api"
SOLO_ZEN_API_ENDPOINT = "https://solo-zen.2miners.com/api"
ETH_API_ENDPOINT = "https://eth.2miners.com/api"
SOLO_ETH_API_ENDPOINT = "https://solo-eth.2miners.com/api"
ERG_API_ENDPOINT = "https://erg.2miners.com/api"
SOLO_ERG_API_ENDPOINT = "https://solo-erg.2miners.com/api"
ETC_API_ENDPOINT = "https://etc.2miners.com/api"
SOLO_ETC_API_ENDPOINT = "https://solo-etc.2miners.com/api"
EXP_API_ENDPOINT = "https://exp.2miners.com/api"
SOLO_EXP_API_ENDPOINT = "https://solo-exp.2miners.com/api"
ETP_API_ENDPOINT = "https://etp.2miners.com/api"
SOLO_ETP_API_ENDPOINT = "https://solo-etp.2miners.com/api"
CLO_API_ENDPOINT = "https://clo.2miners.com/api"
SOLO_CLO_API_ENDPOINT = "https://solo-clo.2miners.com/api"
XMR_API_ENDPOINT = "https://xmr.2miners.com/api"
SOLO_XMR_API_ENDPOINT = "https://solo-xmr.2miners.com/api"
XZC_API_ENDPOINT = "https://xzc.2miners.com/api"
SOLO_XZC_API_ENDPOINT = "https://solo-xzc.2miners.com/api"
ZEL_API_ENDPOINT = "https://zel.2miners.com/api"
SOLO_ZEL_API_ENDPOINT = "https://solo-zel.2miners.com/api"
GRIN_API_ENDPOINT = "https://grin.2miners.com/api"
SOLO_GRIN_API_ENDPOINT = "https://solo-grin.2miners.com/api"
MWC_API_ENDPOINT = "https://mwc.2miners.com/api"
SOLO_MWC_API_ENDPOINT = "https://solo-mwc.2miners.com/api"
RVC_API_ENDPOINT = "https://rvn.2miners.com/api"
SOLO_RVC_API_ENDPOINT = "https://solo-rvn.2miners.com/api"
AE_API_ENDPOINT = "https://ae.2miners.com/api"
SOLO_AE_API_ENDPOINT = "https://solo-ae.2miners.com/api"
BEAM_API_ENDPOINT = "https://beam.2miners.com/api"
SOLO_BEAM_API_ENDPOINT = "https://solo-beam.2miners.com/api"
CTXC_API_ENDPOINT = "https://ctxc.2miners.com/api"
SOLO_CTXC_API_ENDPOINT = "https://solo-ctxc.2miners.com/api"
CKB_API_ENDPOINT = "https://ckb.2miners.com/api"
SOLO_CKB_API_ENDPOINT = "https://solo-ckb.2miners.com/api"

COINGECKO_API_ENDPOINT = "https://api.coingecko.com/api/v3/simple/price?ids="
COINGECKO_API_CURRENCY = "&vs_currencies="

_LOGGER = logging.getLogger(__name__)
